version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/openjdk:9.0.1-jdk
    working_directory: ~/social-network

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

  bundle_dependencies:
      docker:
        - image: circleci/openjdk:9.0.1-jdk
      working_directory: ~/social-network
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
        - run: pwd && ls -lisah
        - run: ./gradlew dependencies
        - save_cache:
            paths:
              - ~/.gradle
            key: v1-dependencies-{{ checksum "build.gradle" }}

  unit_test:
      docker:
        - image: circleci/openjdk:9.0.1-jdk
      working_directory: ~/social-network
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
        - run: ./gradlew test --tests \*Should

  acceptance_test:
      docker:
        - image: circleci/openjdk:9.0.1-jdk
      working_directory: ~/social-network
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
        - run: ./gradlew test --tests \*Feature

  #deploy:
      #deploy options

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - unit_test:
          requires:
            - bundle_dependencies
      - acceptance_test:
          requires:
            - bundle_dependencies
#      - deploy:
#          requires:
#            - unit_test
#            - acceptance_test

